[Interface]
PrivateKey = MCvOd8zICrZlCnwuG2DM+umtOPL+kL3JT38lA3lHsEU=
Address = 10.0.0.2/32
DNS = 8.8.8.8

[Peer]
PublicKey = vh10DKVvD4TDYeEmiEkQaiL6k9GK/vjLP4jJhBjeWx4=
Endpoint = rdseradmin.duckdns.org:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25